/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ExerciseTemplate {
  'id' : bigint,
  'name' : string,
  'sets' : Array<Set>,
  'comments' : string,
}
export interface Set { 'weight' : bigint, 'reps' : bigint }
export interface WorkoutExercise {
  'weight' : number,
  'exerciseId' : bigint,
  'reps' : bigint,
  'sets' : bigint,
  'exerciseName' : string,
  'comments' : string,
}
export interface WorkoutSession {
  'id' : bigint,
  'isCompleted' : boolean,
  'date' : bigint,
  'name' : string,
  'exercises' : Array<WorkoutExercise>,
}
export interface WorkoutSessionHistory {
  'id' : bigint,
  'isCompleted' : boolean,
  'date' : bigint,
  'name' : string,
  'exercises' : Array<WorkoutExercise>,
}
export interface _SERVICE {
  'addExercise' : ActorMethod<[string], bigint>,
  'addExerciseToSession' : ActorMethod<
    [bigint, bigint, number, bigint, bigint, string],
    undefined
  >,
  'createWorkoutSession' : ActorMethod<[string, bigint], bigint>,
  'deleteExercise' : ActorMethod<[bigint], undefined>,
  'editExercise' : ActorMethod<[bigint, string], undefined>,
  'getAllExercises' : ActorMethod<[], Array<ExerciseTemplate>>,
  'getExerciseLibrarySize' : ActorMethod<[], bigint>,
  'getNextExerciseId' : ActorMethod<[], bigint>,
  'getNextSessionId' : ActorMethod<[], bigint>,
  'getSessionExercises' : ActorMethod<[bigint], Array<WorkoutExercise>>,
  'getWorkoutHistory' : ActorMethod<[], Array<WorkoutSessionHistory>>,
  'getWorkoutSessionsByDate' : ActorMethod<[], Array<WorkoutSession>>,
  'removeExerciseFromSession' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];