/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Set = IDL.Record({ 'weight' : IDL.Nat, 'reps' : IDL.Nat });
export const ExerciseTemplate = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'sets' : IDL.Vec(Set),
  'comments' : IDL.Text,
});
export const WorkoutExercise = IDL.Record({
  'weight' : IDL.Float64,
  'exerciseId' : IDL.Nat,
  'reps' : IDL.Nat,
  'sets' : IDL.Nat,
  'exerciseName' : IDL.Text,
  'comments' : IDL.Text,
});
export const WorkoutSessionHistory = IDL.Record({
  'id' : IDL.Nat,
  'isCompleted' : IDL.Bool,
  'date' : IDL.Int,
  'name' : IDL.Text,
  'exercises' : IDL.Vec(WorkoutExercise),
});
export const WorkoutSession = IDL.Record({
  'id' : IDL.Nat,
  'isCompleted' : IDL.Bool,
  'date' : IDL.Int,
  'name' : IDL.Text,
  'exercises' : IDL.Vec(WorkoutExercise),
});

export const idlService = IDL.Service({
  'addExercise' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'addExerciseToSession' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Float64, IDL.Nat, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'createWorkoutSession' : IDL.Func([IDL.Text, IDL.Int], [IDL.Nat], []),
  'deleteExercise' : IDL.Func([IDL.Nat], [], []),
  'editExercise' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'getAllExercises' : IDL.Func([], [IDL.Vec(ExerciseTemplate)], ['query']),
  'getExerciseLibrarySize' : IDL.Func([], [IDL.Nat], ['query']),
  'getNextExerciseId' : IDL.Func([], [IDL.Nat], ['query']),
  'getNextSessionId' : IDL.Func([], [IDL.Nat], ['query']),
  'getSessionExercises' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(WorkoutExercise)],
      ['query'],
    ),
  'getWorkoutHistory' : IDL.Func(
      [],
      [IDL.Vec(WorkoutSessionHistory)],
      ['query'],
    ),
  'getWorkoutSessionsByDate' : IDL.Func(
      [],
      [IDL.Vec(WorkoutSession)],
      ['query'],
    ),
  'removeExerciseFromSession' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Set = IDL.Record({ 'weight' : IDL.Nat, 'reps' : IDL.Nat });
  const ExerciseTemplate = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'sets' : IDL.Vec(Set),
    'comments' : IDL.Text,
  });
  const WorkoutExercise = IDL.Record({
    'weight' : IDL.Float64,
    'exerciseId' : IDL.Nat,
    'reps' : IDL.Nat,
    'sets' : IDL.Nat,
    'exerciseName' : IDL.Text,
    'comments' : IDL.Text,
  });
  const WorkoutSessionHistory = IDL.Record({
    'id' : IDL.Nat,
    'isCompleted' : IDL.Bool,
    'date' : IDL.Int,
    'name' : IDL.Text,
    'exercises' : IDL.Vec(WorkoutExercise),
  });
  const WorkoutSession = IDL.Record({
    'id' : IDL.Nat,
    'isCompleted' : IDL.Bool,
    'date' : IDL.Int,
    'name' : IDL.Text,
    'exercises' : IDL.Vec(WorkoutExercise),
  });
  
  return IDL.Service({
    'addExercise' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'addExerciseToSession' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Float64, IDL.Nat, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'createWorkoutSession' : IDL.Func([IDL.Text, IDL.Int], [IDL.Nat], []),
    'deleteExercise' : IDL.Func([IDL.Nat], [], []),
    'editExercise' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'getAllExercises' : IDL.Func([], [IDL.Vec(ExerciseTemplate)], ['query']),
    'getExerciseLibrarySize' : IDL.Func([], [IDL.Nat], ['query']),
    'getNextExerciseId' : IDL.Func([], [IDL.Nat], ['query']),
    'getNextSessionId' : IDL.Func([], [IDL.Nat], ['query']),
    'getSessionExercises' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(WorkoutExercise)],
        ['query'],
      ),
    'getWorkoutHistory' : IDL.Func(
        [],
        [IDL.Vec(WorkoutSessionHistory)],
        ['query'],
      ),
    'getWorkoutSessionsByDate' : IDL.Func(
        [],
        [IDL.Vec(WorkoutSession)],
        ['query'],
      ),
    'removeExerciseFromSession' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };