/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface WorkoutSessionHistory {
    id: bigint;
    isCompleted: boolean;
    date: bigint;
    name: string;
    exercises: Array<WorkoutExercise>;
}
export interface ExerciseTemplate {
    id: bigint;
    name: string;
    sets: Array<Set_>;
    comments: string;
}
export interface WorkoutSession {
    id: bigint;
    isCompleted: boolean;
    date: bigint;
    name: string;
    exercises: Array<WorkoutExercise>;
}
export interface WorkoutExercise {
    weight: number;
    exerciseId: bigint;
    reps: bigint;
    sets: bigint;
    exerciseName: string;
    comments: string;
}
export interface Set_ {
    weight: bigint;
    reps: bigint;
}
export interface backendInterface {
    addExercise(name: string): Promise<bigint>;
    addExerciseToSession(sessionId: bigint, exerciseId: bigint, weight: number, reps: bigint, sets: bigint, comments: string): Promise<void>;
    createWorkoutSession(name: string, date: bigint): Promise<bigint>;
    deleteExercise(id: bigint): Promise<void>;
    editExercise(id: bigint, newName: string): Promise<void>;
    getAllExercises(): Promise<Array<ExerciseTemplate>>;
    getExerciseLibrarySize(): Promise<bigint>;
    getNextExerciseId(): Promise<bigint>;
    getNextSessionId(): Promise<bigint>;
    getSessionExercises(sessionId: bigint): Promise<Array<WorkoutExercise>>;
    getWorkoutHistory(): Promise<Array<WorkoutSessionHistory>>;
    getWorkoutSessionsByDate(): Promise<Array<WorkoutSession>>;
    removeExerciseFromSession(sessionId: bigint, exerciseIndex: bigint): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addExercise(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addExercise(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExercise(arg0);
            return result;
        }
    }
    async addExerciseToSession(arg0: bigint, arg1: bigint, arg2: number, arg3: bigint, arg4: bigint, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addExerciseToSession(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExerciseToSession(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createWorkoutSession(arg0: string, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createWorkoutSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWorkoutSession(arg0, arg1);
            return result;
        }
    }
    async deleteExercise(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExercise(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExercise(arg0);
            return result;
        }
    }
    async editExercise(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editExercise(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editExercise(arg0, arg1);
            return result;
        }
    }
    async getAllExercises(): Promise<Array<ExerciseTemplate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExercises();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExercises();
            return result;
        }
    }
    async getExerciseLibrarySize(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getExerciseLibrarySize();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExerciseLibrarySize();
            return result;
        }
    }
    async getNextExerciseId(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getNextExerciseId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNextExerciseId();
            return result;
        }
    }
    async getNextSessionId(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getNextSessionId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNextSessionId();
            return result;
        }
    }
    async getSessionExercises(arg0: bigint): Promise<Array<WorkoutExercise>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionExercises(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionExercises(arg0);
            return result;
        }
    }
    async getWorkoutHistory(): Promise<Array<WorkoutSessionHistory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutHistory();
            return result;
        }
    }
    async getWorkoutSessionsByDate(): Promise<Array<WorkoutSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutSessionsByDate();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutSessionsByDate();
            return result;
        }
    }
    async removeExerciseFromSession(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeExerciseFromSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeExerciseFromSession(arg0, arg1);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
